---
title: "Density-dependent pregnancy rates"
author: "Max Czapanskiy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(lubridate)
library(tidyverse)
```

## Population sizes

Christensen et al. (2006) reconstructed population sizes of whale populations.

```{r read_pops}
whale_pops <- readxl::read_excel("analysis/data/raw_data/Whale_pops_time_Christensen 2006.xlsx") %>% 
  # Years have decimals for some reason
  mutate(Year = floor(Year),
         # Sperm Whale populations weren't broken down by hemisphere, so
         # we're just using the global population for now
         Region = ifelse(CommonName == "Sperm Whale",
                         "Southern Hemisphere",
                         Region))
glimpse(whale_pops)
```

```{r whale_pops_ts}
whale_pops %>% 
  filter(between(Year, 1900, 2000),
         CommonName %in% c("Blue Whale",
                           "Fin Whale",
                           "Sperm Whale"),
         Region == "Southern Hemisphere") %>% 
  mutate(Pop_size = Pop_size / 1000) %>% 
  ggplot(aes(Year, Pop_size, color = CommonName)) +
  geom_line() +
  scale_y_continuous("Population size (1000s)") +
  theme_classic() +
  theme(legend.position = "bottom",
        legend.title = element_blank())
```

## Density-dependent pregnancy rates

```{r iwc}
whale_catches <- readRDS("analysis/data/derived_data/great_whales_iwc.RDS") %>% 
  filter(species %in% c("Blue",
                        "Fin",
                        "Sperm")) %>% 
  mutate(species = paste(as.character(species), "Whale"))

whale_preg <- whale_catches %>% 
  filter(sex == "Female") %>% 
  drop_na(latitude) %>% 
  mutate(Hemisphere = ifelse(latitude < 0, "S", "N")) %>% 
  group_by(Year = catch_year,
           CommonName = species,
           Hemisphere) %>% 
  summarize(n_f_catch = n(),
            preg_rate = sum(is_pregnant) / n(),
            .groups = "drop") %>% 
  filter(n_f_catch >= 10)
```

```{r ddpr}
sh_whales <- whale_pops %>% 
  filter(between(Year, 1800, 2000),
         Region == "Southern Hemisphere",
         CommonName %in% c("Blue Whale", "Fin Whale", "Sperm Whale")) %>% 
  left_join(filter(whale_preg, Hemisphere == "S"), 
            by = c("Year", "CommonName"))

ggplot(sh_whales, aes(Pop_size / 1000, preg_rate)) + 
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(cols = vars(CommonName), scales = "free_x") +
  scale_y_continuous("Pregnancy Rate", labels = scales::percent) +
  scale_color_manual(values = c(`TRUE` = "red", `FALSE` = "blue")) +
  labs(x = "Population (1000s)") +
  expand_limits(x = 0, y = 0) +
  theme_classic()
```

Catches and populations over time
```{r catch_pop}
sh_catches <- whale_catches %>% 
  drop_na(latitude) %>% 
  filter(latitude < 0, species != "Antarctic Minke Whale") %>% 
  group_by(Year = catch_year,
           CommonName = species) %>% 
  summarize(Catches = n(), .groups = "drop")

ggplot() + 
  geom_line(aes(Year, Pop_size / 1000),
            filter(sh_whales, between(Year, 1900, 1990)),
            color = "blue",
            size = 1) +
  # geom_line(aes(Year, Catches / 1000),
  #           filter(sh_catches, between(Year, 1900, 1990)),
  #           color = "red",
  #           size = 1) +
  facet_grid(cols = vars(CommonName), scales = "free_x") +
  labs(y = "Population (1000s)") +
  theme_classic(base_size = 24)
```

```{r preg_model}
# Normalize population sizes wrt k, assuming max pop size is k
preg_wide <- sh_whales %>% 
  group_by(CommonName) %>% 
  mutate(pop_norm = Pop_size / max(Pop_size),
         n_preg = floor(n_f_catch * preg_rate)) %>% 
  ungroup() %>% 
  drop_na(n_preg) %>% 
  filter(between(Year, 1900, 1990))

# Fit the model for populations greater than k/5
preg_data <- filter(preg_wide, pop_norm >= 0.2)
preg_glm <- glm(preg_rate ~ pop_norm * CommonName, 
                data = preg_data, 
                family = binomial,
                weights = n_f_catch)

# Plot results
preg_grid <- expand_grid(
  CommonName = unique(preg_wide$CommonName),
  pop_norm = seq(0.2, 1, length.out = 100)
)
preg_pred <- predict(preg_glm, newdata = preg_grid, type = "link", se.fit = TRUE)
invlink_fun <- family(preg_glm)$linkinv
preg_grid$preg_rate <- invlink_fun(preg_pred$fit)
preg_grid$preg_rate_lwr <- invlink_fun(preg_pred$fit - 2 * preg_pred$se.fit)
preg_grid$preg_rate_upr <- invlink_fun(preg_pred$fit + 2 * preg_pred$se.fit)
# Constrain to interpolating pop sizes
pop_constraints <- preg_data %>% 
  group_by(CommonName) %>% 
  summarize(min_pop = min(pop_norm),
            max_pop = max(pop_norm),
            .groups = "drop")
preg_grid <- preg_grid %>% 
  left_join(pop_constraints, by = "CommonName") %>% 
  filter(pop_norm >= min_pop,
         pop_norm <= max_pop)

pal <- c(
  "Fin Whale" = "#4CA888",
  "Blue Whale" = "#7DC0EA",
  "Sperm Whale" = "#E3B03C"
)

ggplot(preg_grid, aes(pop_norm, preg_rate, color = CommonName)) +
  geom_point(aes(size = n_f_catch), preg_wide, shape = 21) +
  geom_ribbon(aes(fill = CommonName, 
                  ymin = preg_rate_lwr, 
                  ymax = preg_rate_upr),
              alpha = 0.25,
              color = NA) +
  geom_line() +
  scale_color_manual(values = pal) +
  scale_fill_manual(values = pal) +
  labs(x = "Population size (normalized)",
       y = "Pregnancy probability",
       color = "",
       fill = "",
       size = "Females caught (annual)") +
  theme_classic(base_size = 24) +
  theme(legend.position = "bottom",
        legend.box = "vertical")
```

```{r data_summary}
preg_data %>% 
  group_by(CommonName) %>% 
  summarize(n_years = n(),
            min_year = min(Year),
            max_year = max(Year),
            n_f = sum(n_f_catch),
            pop_range = (max(Pop_size) - min(Pop_size)) / max(Pop_size))
```


```{r preg_coef}
library(emmeans)
library(ggsignif)
preg_em <- emtrends(preg_glm, "CommonName", "pop_norm")
preg_pairs <- as_tibble(pairs(preg_em)) %>% 
  mutate(comparisons = str_split(contrast, " - "),
         annotations = sprintf("p = %.7f", signif(p.value, 2)),
         # remove trailing zeros
         annotations = str_remove(annotations, "0+$"))
plot(preg_em,
     xlab = "Coef") +
  geom_signif(
    comparisons = preg_pairs$comparisons,
    annotations = preg_pairs$annotations,
    step_increase = 0.1
  ) +
  expand_limits(x = 0) +
  theme_classic() +
  theme(axis.title.y = element_blank())
```

```{r lht_var}
whale_lht <- preg_grid %>% 
  group_by(CommonName) %>% 
  summarize(pop_var = (max(pop_norm) - min(pop_norm)) / max(pop_norm),
            preg_var = (max(preg_rate) - min(preg_rate)) / max(preg_rate),
            lht_var = preg_var / pop_var) %>% 
  mutate(y = c(2.8, 3.2, 3.0))

ggplot(whale_lht) +
  annotate("rect", 
           xmin = 0.12, xmax = 0.49, ymin = 1, ymax = 2,
           fill = NA,
           color = "black") +
  annotate("segment", x = 0.3, xend = 0.3, y = 1, yend = 2) +
  geom_point(aes(lht_var, y, color = CommonName), size = 10) +
  scale_color_manual(values = pal) +
  expand_limits(x = 0, y = c(0.5, 3.5)) +
  labs(x = "Density dependence") +
  theme_classic(base_size = 24) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())
```
