---
title: "Life history oddballs"
author: "Max Czapanskiy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r init}
library(ape)
library(dplyr)
library(ggplot2)
library(here)
library(nlme)
library(purrr)
library(readr)
library(rotl)
library(tidyr)
```

# Scaling of life history traits

Quantifying great whales' pace-of-life 

## Life history traits

From [Myhrvold et al. (2015) *Ecology*](https://doi.org/10.1890/15-0846R.1)

```{r lht}
mammal_lht <- read_csv(
  here("analysis", "data", "raw_data", "Amniote_Database_Aug_2015.csv"),
) %>% 
  mutate(
    across(everything(), ~ na_if(.x, -999)),
    inter_birth_interval_y = 1 / litters_or_clutches_per_y,
    adult_body_mass_kg = adult_body_mass_g,
    gestation_weaning_d = gestation_d + weaning_d,
    great_whale = case_when(
      paste(genus, species) == "Balaenoptera musculus"  ~ "Blue Whale",
      paste(genus, species) == "Balaenoptera physalus"  ~ "Fin Whale",
      # Note outdated species name
      paste(genus, species) == "Physeter catodon" ~ "Sperm Whale",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(class == "Mammalia")

life_history_plot <- function(param_col, param_pretty) {
  lbls_exp <- function(brks) {
    round(exp(brks), 1)
  }
  pal <- c(
  "Blue Whale" = "#7DC0EA",
  "Fin Whale" = "#4CA888",
  "Sperm Whale" = "#E3B03C",
  `NA` = "black"
)
  mammal_lht %>% 
    drop_na(adult_body_mass_g, {{ param_col }}) %>% 
    mutate(log_mass = log(adult_body_mass_kg),
           log_param = log({{ param_col }})) %>% 
    ggplot(aes(log_mass, log_param)) +
    geom_point(aes(color = great_whale)) +
    geom_smooth(method = "lm", formula = y ~ x) +
    scale_color_manual(values = pal) +
    scale_x_continuous("Adult mass (kg)", 
                       labels = lbls_exp) +
    scale_y_continuous(param_pretty, 
                       labels = lbls_exp) +
    expand_limits(x = 0, y = 0) +
    theme_classic() +
    theme(legend.position = "none")
}

lht_plots <- map2(
  quos(female_maturity_d, gestation_weaning_d, longevity_y, 
       litter_or_clutch_size_n, inter_birth_interval_y),
  c("Female age at maturity (days)", "Gestation + Weaning (days)", 
    "Longevity (years)", "Fecundity (n offspring)", "Inter-birth interval (y)"),
  life_history_plot
)
print(lht_plots)
```

## With phylogeny

Now correct for phylogeny. Using mammal tree from [Upham et al. (2019) *PLOS*](https://doi.org/10.1371/journal.pbio.3000494), downloaded from [VertLife](http://verlife.org/phylosubsets).

```{r resolve_tax}
# There are 100 trees in the nexus file because they're generated probabilistically.
mammal_trs <- read.nexus(here("analysis", "data", "raw_data", "mammals.nex"))
# We'll try the analysis on the first one
mammal_tr <- mammal_trs[[1]]

# 344 species are in the life history trait database but not the phylogeny. I 
# manually verified the results of rotl::tnrs_match_names() to resolve 
# taxonomic disagreements. Results of manual audit saved to CSV file.
lht_tax_missing <- mammal_lht %>% 
  mutate(binomial = paste(genus, species, sep = "_"),
         binomial2 = paste(genus, species, sep = " "),
         in_tree = binomial %in% mammal_tr$tip.label) %>% 
  filter(!in_tree) %>% 
  pull(binomial2)
lht_tax <- tnrs_match_names(lht_tax_missing,
                            context_name = "Mammals")
head(lht_tax)

# As a result of taxonomy resolution, some species were lumped. Aggregate
# their life history traits by the median. Drop species with incomplete LHT
# records.
lht_tax_resolutions <- here("analysis", "data", "raw_data", "tnr_lht.csv") %>% 
  read_csv() %>% 
  drop_na(corrected_name) %>% 
  select(search_string, corrected_name)
mammal_lht_resolved <- mammal_lht %>% 
  mutate(search_string = trimws(tolower(paste(genus, species)))) %>% 
  left_join(lht_tax_resolutions, by = "search_string") %>% 
  mutate(tree_name = coalesce(corrected_name, paste(genus, species, sep = "_")),
         in_tree = tree_name %in% mammal_tr$tip.label) %>% 
  filter(in_tree) %>% 
  select(tree_name, adult_body_mass_kg, female_maturity_d, gestation_weaning_d, 
         longevity_y, litter_or_clutch_size_n, inter_birth_interval_y) %>% 
  drop_na() %>% 
  group_by(tree_name) %>% 
  summarize(across(everything(), median, na.rm = TRUE))
# Leaves 1322 species

# Subset tree to retained species
mammal_tr_subset <- keep.tip(mammal_tr, mammal_lht_resolved$tree_name)
```

Calculate size residuals. See [Jeschke and Kokko (2009)](https://doi.org/10.1007/s10682-008-9276-y) *Evolutionary Ecology*

```{r size_resid}
# lht should be a column name e.g. "female_maturity_d"
fit_pgls <- function(lht) {
  f <- update(~ log(adult_body_mass_kg), 
              as.formula(sprintf("log(%s) ~ .", lht)))
  cor <- corBrownian(phy = mammal_tr_subset, form = ~ tree_name)
  gls(f, mammal_lht_resolved, cor, method = "ML")
}
pgls_models <- map(
  c("female_maturity_d", "gestation_weaning_d", "longevity_y", 
    "litter_or_clutch_size_n", "inter_birth_interval_y"),
  fit_pgls
)
mammal_lht_size <- mammal_lht_resolved %>% 
  mutate(female_maturity_d_resid = resid(pgls_models[[1]]),
         gestation_weaning_d_resid = resid(pgls_models[[2]]),
         longevity_y_resid = resid(pgls_models[[3]]),
         litter_or_clutch_size_n_resid = resid(pgls_models[[4]]),
         inter_birth_interval_y_resid = resid(pgls_models[[5]]))
```

```{r lht_pca}
# PCA analysis
pca_mtx <- mammal_lht_size %>% 
  tibble::column_to_rownames("tree_name") %>% 
  mutate(across(ends_with("resid"), ~ (.x - mean(.x)) / sd(.x))) %>% 
  select(ends_with("resid")) %>% 
  as.matrix()
lht_pca <- prcomp(pca_mtx, center = FALSE, scale = FALSE)
lht_loadings <- as.data.frame(lht_pca$rotation)
lht_scores <- predict(lht_pca)
lht_importance <- summary(lht_pca)$importance
pc1_var <- lht_importance["Proportion of Variance", "PC1"]
pc2_var <- lht_importance["Proportion of Variance", "PC2"]

# Plot
mammal_lht_pca <- mammal_lht_size %>% 
  mutate(pca1 = lht_scores[, 1],
         pca2 = lht_scores[, 2])
ggplot(mammal_lht_pca, aes(pca1, pca2)) +
  geom_point(alpha = 0.5) +
  geom_segment(aes(x = 0, y = 0, xend = PC1, yend = PC2),
               lht_loadings,
               arrow = arrow(length = unit(0.03, "npc")), 
               alpha = 0.2) +
  geom_text(aes(x = PC1, y = PC2, label = rownames(lht_loadings)),
            lht_loadings) +
  labs(
    x = sprintf("PC1 (%0.1f%%)", round(pca1_var * 100, 1)),
    y = sprintf("PC2 (%0.1f%%)", round(pca2_var * 100, 1))
  ) +
  coord_fixed() +
  theme_classic()
```


